### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by mkrappitz** [CodersCare/gridelements#81]
We have the following language setup in TYPO3 12.4.27 and gridelements 12.0.0 (TER version) and php 8.2.27 on a Mittwald hosting:

```yaml
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /en/
    typo3Language: default
    locale: en_GB.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en
    direction: ''
    flag: gb
    websiteTitle: ''
  -
    title: German
    enabled: true
    base: /de/
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    websiteTitle: ''
    navigationTitle: Deutsch
    hreflang: de
    direction: ''
    fallbackType: strict
    fallbacks: ''
    flag: de
    languageId: 3
```

There is some strange behaviour when working with a translated content element and an untranslated gridelement. 

Initial steps to reproduce:
- Create a new page in EN and translate it to DE.
- Create a new standard (for example) text content element in EN and translate it to DE with connected mode.
- Create a new gridelement with minimum one column in DE on the same page.

Then the following stuff happens, if you move the translated text element into the grid element in the default EN language, this is how it looks after the drag & drop - first all fine:
![Image](https://github.com/user-attachments/assets/e06abdef-c832-46e9-93ce-783c55389339)

But if you just refresh the current view in the page module, it looks like this, the DE translation of the text element "jumped" into the default language grid element:
![Image](https://github.com/user-attachments/assets/d06e803a-f181-4315-8311-88c608b8531e)

If you then try to "fix" this by translating the grid element to DE in connected mode, you then have 2 DE translations of the text element, one in the default language gridelement, one in the translated language gridelement:
![Image](https://github.com/user-attachments/assets/c77f6ea1-aa63-4055-9b93-b593d05c8ca8)
And in the frontend it even renders correctly in the default language, you only see the gridelement with the default language text element. But in the translated language you see the gridelement and both translated language text elements inside:
![Image](https://github.com/user-attachments/assets/ec5f5f18-fa73-4ae2-a11c-5d3ab714e7b9)

You can then finally "fix" that by deleting the superflous translated text element in the default language. Anyway this behaviour seems erratic to me and should be fixed, if this is something caused by gridelements.
